version: '3'

services:
  api:
    image: inspirit941/openai-whisper-streamlit:downsize_image
    environment:
      - model=whisper_wak
      - model_2=whisper-mobi-240418
      - CHUNK_SIZE=30
    ports:
      - "21400:8501"
    volumes:
      - ./downloads:/app/downloads
      - ./transcripts:/app/transcripts
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
