name: Build and Push Docker Image
on:
  push:
    branches: [ "main", "feature/downsize_image" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t inspirit941/openai-whisper-streamlit:${GITHUB_REF##*/} .

      - name: Push Docker image
        run: docker push your_username/your_image_name:${GITHUB_REF##*/}
